Crud_Application/Models/Loginclass.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Crud_Application.Models
{
    public class Loginclass
    {
        [Required(ErrorMessage = "Enter the Username")]
        public string uname { get; set; }
        [Required(ErrorMessage = "Enter the Password")]
        public string pwd { get; set; }

        public string msg { get; set; }
    }
}

Crud_Application/Models/profilecls.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Crud_Application.Models
{
    public class profilecls
    {
        public string Name { get; set; }
        public string Emai { get; set; }
        public string Mobileno { get; set; }
        public string Country { get; set; }
        public string Image { get; set; }
        public string msg { get; set; }
    }
}

Crud_Application/Models/userinsert.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Crud_Application.Models
{
    public class userinsert
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Enter the Name")]
        public string Name { get; set; }

        [EmailAddress(ErrorMessage = "Enter correct formar")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Phone Number Required!")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
                   ErrorMessage = "Entered phone format is not valid.")]
        public string Mobileno { get; set; }
        public string Country { get; set; }
        public string Image { get; set; }
        
        public string Username { get; set; }

        public string Password { get; set; }

        [Compare("Password", ErrorMessage = "Password Mismatch")]
        public string ConfirmPassword { get; set; }

        public string msg { get; set; }
    }
}

Crud_Application/Controllers/DashController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Crud_Application.Models;

namespace Crud_Application.Controllers
{
    public class DashController : Controller
    {
        // GET: Dash
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Dash_load()
        {
           
            WebappEntities dbobj = new WebappEntities();
            var getdata = dbobj.sp_dashboard();
            
             return View(dbobj.User_Reg.ToList());


        }
    }
}

Crud_Application/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Crud_Application.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Crud_Application/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Crud_Application.Models;

namespace Crud_Application.Controllers
{
    public class ProfileController : Controller
    {
        // GET: Profile
        public ActionResult Profileload()
        {
            WebappEntities dbobj = new WebappEntities();
            var getdata = dbobj.sp_profile(Session["uname"].ToString()).FirstOrDefault();
            return View(new profilecls
            {
                Name = getdata.Name,
                Emai = getdata.Emai,
                Mobileno=getdata.Mobileno,
                Country=getdata.Country,
                Image=getdata.Image,


            });
        }
        
        public ActionResult profile_update(profilecls obj)
        {
            if (ModelState.IsValid && false)
            {
                WebappEntities dbobj = new WebappEntities();
                dbobj.sp_profile_update(Session["uname"].ToString(), obj.Name, obj.Emai, obj.Mobileno, obj.Country, obj.Image);
                obj.msg = "Successfully Updated";
                return View("Profileload", obj);

            }
            return View("Profileload", obj);
        }


    //    public ActionResult Profile_delete(profilecls obj1)
    //    {
    //        if (ModelState.IsValid)
    //        {
    //            WebappEntities dbobj1 = new WebappEntities();
    //            dbobj1.sp_delete();
    //            obj1.msg = "Successfully Updated";
    //            return View("Profileload", obj1);

    //        }
    //        return View("Profileload", obj1);
    //    }
    //}

    public ActionResult Profile_signout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("login_page", "User_Log");
        }
    }
}

Crud_Application/Controllers/User_LogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity.Core.Objects;
using Crud_Application.Models;

namespace Crud_Application.Controllers
{
    public class User_LogController : Controller
    {
        // GET: User_Log
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult login_page()
        {
            
            return View();
        }

        public ActionResult Home()
        {
            return View();
        }

        public ActionResult login_click(Loginclass ob)
        {
            if (ModelState.IsValid)
            {
                WebappEntities dbobj = new WebappEntities();
                ObjectParameter op = new ObjectParameter("status", typeof(int));
                dbobj.sp_login(ob.uname, ob.pwd, op);
                int outputvalue = Convert.ToInt32(op.Value);
                if (outputvalue == 1)
                {
                    Session["uname"] = ob.uname;
                    // return RedirectToAction("login_page", ob);
                    return RedirectToAction("Dash_load", "Dash", ob);
                    

                }
                else
                {
                    ob.msg = "Invalid Username and Password";
                    return RedirectToAction("login_page", ob);
                }
            }
            return RedirectToAction("login_page", ob);
        }
    }
}

Crud_Application/Controllers/User_RegController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Crud_Application.Models;

namespace Crud_Application.Controllers
{
    public class User_RegController : Controller
    {
        // GET: User_Reg
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult reg_pageload()
        {
            return View();

        }

        public ActionResult reg_click(userinsert ob, HttpPostedFileBase file)
        {

            if (ModelState.IsValid)
            {
                if (file.ContentLength > 0)
                {
                    String filename = Path.GetFileName(file.FileName);
                    String p = Path.Combine(Server.MapPath("/Image"), filename);
                    file.SaveAs(p);
                    var pa = Path.Combine("~//Image", filename);
                    ob.Image = pa;
                }
               WebappEntities dbobj = new WebappEntities();
                dbobj.sp_insert(ob.Name, ob.Email, ob.Mobileno, ob.Country, ob.Image, ob.Username, ob.Password);
                ob.msg = "Successfully Inserted";
                ModelState.Clear();
                return View("reg_pageload", ob);
            }
            return View("reg_pageload", ob);
        }
    }
}

Crud_Application/Views/Dash/Dash_load.cshtml
@model IEnumerable<Crud_Application.User_Reg>
@{
    ViewBag.Title = "Dash_load";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>User Details</h2>
<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Email
        </th>
        <th>
            MobileNumber
        </th>
        <th>
            Country
        </th>
        
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Emai)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Mobileno)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Country)
    </td>
    <td>
        @Html.ActionLink("Edit", "profile_update","Profile", item,null) |
        @Html.ActionLink("Delete", "Profile_delete", new { id = item.id }) |
        
    </td>

</tr>
    }

</table>

Crud_Application/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Crud_Application/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Crud_Application/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Crud_Application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CRUD Web Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <% if(Context.User.Identity.IsAuthenticated) { %>
                    <li>@Html.ActionLink("Dashboard", "Dash_load", "Dash")</li>
                    <li>@Html.ActionLink("User Creation", "reg_pageload", "User_Reg")</li>
                    <li>@Html.ActionLink("Signout", "login_page", "User_Log")</li>
                    <% } %>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Crud_Application/Views/User_Log/Home.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Home</h2>
Welcome @Session["uname"]
<div>
    @Html.ActionLink("View Profile", "Profileload", "Profile")
</div>

Crud_Application/Views/User_Log/login_page.cshtml
@model Crud_Application.Models.Loginclass
@{
    ViewBag.Title = "login_page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>User Login</h2>
<div>
    @using (Html.BeginForm("login_click", "User_Log", FormMethod.Post))
    {
        <div><label>User Name</label></div>
        <div>
            @Html.TextBoxFor(m => m.uname)
            @Html.ValidationMessageFor(m => m.uname)
        </div>

        <div><label>Password</label></div>
        <div>
            @Html.PasswordFor(m => m.pwd)
            @Html.ValidationMessageFor(m => m.pwd)
        </div>

        <div>
            <input type="submit" value="Login" />
            @Html.DisplayFor(m => m.msg)
        </div>
    }
</div>

Crud_Application/Views/User_Reg/reg_pageload.cshtml
@model Crud_Application.Models.userinsert
@{
    ViewBag.Title = "reg_pageload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>reg_pageload</h2>

<div>
    @using (Html.BeginForm("reg_click", "User_Reg", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div><label>Name</label></div>
        <div>
            @Html.TextBoxFor(m => m.Name)
            @Html.ValidationMessageFor(m => m.Name)
        </div>


        <div><label>Email</label></div>
        <div>
            @Html.TextBoxFor(m => m.Email)
            @Html.ValidationMessageFor(m => m.Email)
        </div>

        <div><label>Mobile Number</label></div>
        <div>
            @Html.TextBoxFor(m => m.Mobileno)
            @Html.ValidationMessageFor(m => m.Mobileno)
        </div>

        <div><label>Country</label></div>
        <div>
            @Html.TextBoxFor(m => m.Country)
            @Html.ValidationMessageFor(m => m.Country)
        </div>

        <div><label>Photo</label></div>
        <div>
            @Html.TextBox("file", "", new { Type = "file" })
        </div>

        <div><label>Username</label></div>
        <div>
            @Html.TextBoxFor(m => m.Username)
            @Html.ValidationMessageFor(m => m.Username)
        </div>

        <div><label>Password</label></div>
        <div>
            @Html.PasswordFor(m => m.Password)
            @Html.ValidationMessageFor(m => m.Password)
        </div>

        <div><label>ConfirmPassword</label></div>
        <div>
            @Html.PasswordFor(m => m.ConfirmPassword)
            @Html.ValidationMessageFor(m => m.ConfirmPassword)
        </div>

        <div>
            <input type="submit" value="Register" />
            @Html.DisplayFor(m => m.msg)
        </div>
    }
</div>